# Generated by Django 2.1.3 on 2018-11-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(default='None', max_length=128)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=128, null=True)),
                ('education_type', models.CharField(max_length=128, null=True)),
                ('budget_plan', models.IntegerField(null=True)),
                ('budget_passing_score', models.IntegerField(null=True)),
                ('paid_plan', models.IntegerField(null=True)),
                ('paid_passing_score', models.IntegerField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Specialty')),
                ('subjects', models.ManyToManyField(to='core.Subject')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.University')),
            ],
        ),
    ]
