# Generated by Django 2.1.3 on 2018-11-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='city',
        ),
        migrations.AddField(
            model_name='university',
            name='place',
            field=models.IntegerField(default=None),
        ),
    ]
