# Generated by Django 2.1.3 on 2018-11-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181120_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
