# Generated by Django 2.1.3 on 2018-11-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181120_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='place',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
