# Generated by Django 2.1.3 on 2018-11-25 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181125_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='applicants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
